import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { PalmasLakeLeadForm } from "@/components/public/palmas-lake-lead-form";
import { PalmasLakeWhatsAppBubble } from "@/components/public/palmas-lake-whatsapp-bubble";
import { Anchor, ArrowDownRight, ArrowUpRight, Building2, BriefcaseBusiness, ChevronDown, MapPin, Plane, ShieldCheck, Sparkles, Waves } from "lucide-react";
import { getSiteUrl } from "@/lib/site-url";

const baseUrl = getSiteUrl();
export const metadata: Metadata = {
  title: "Palmas Lake | Onde a vida se eleva",
  description: "Conheça o Palmas Lake: um complexo multifuncional à beira do lago, com seis experiências entre morar, trabalhar, investir e viver Palmas.",
  alternates: { canonical: `${baseUrl}/palmas-lake` },
  openGraph: { type: "website", locale: "pt_BR", url: `${baseUrl}/palmas-lake`, title: "Palmas Lake | Onde a vida se eleva", description: "Seis experiências, um endereço único à beira do lago.", images: [{ url: "/brand/palmas-lake/hero-principal.png", width: 1448, height: 713, alt: "Palmas Lake, Marina e torres residenciais ao pôr do sol" }] }
};

const whatsappHref = "https://wa.me/5563984845101?text=Ol%C3%A1%20Pedro%2C%20quero%20conhecer%20o%20Palmas%20Lake.";
const developments = [
  ["lake-sky", "Lake Sky", "Residencial · 2032", "O topo do Palmas Lake.", "Coberturas duplex e mansões suspensas com vista permanente para o lago.", "331 a 663 m² · 4 suítes · 4 a 6 vagas", "sky"],
  ["lake-garden", "Lake Garden", "Residencial · 2032", "Alto luxo residencial.", "Espaço, paisagismo exuberante e a calma de morar de frente para o lago.", "222,70 m² · 3 ou 4 suítes · 3 vagas", "garden"],
  ["lake-park", "Lake Park", "Residencial · 2032", "Conforto que respira.", "Plantas amplas, living integrado e um ponto de entrada especial no residencial.", "189 a 192 m² · 3 suítes · 2 vagas", "park"],
  ["lake-loft", "Lake Loft", "Multifuncional · 2029", "Morar. Hospedar. Investir.", "Compactos inteligentes preparados para a vida contemporânea e a renda por hospedagem.", "44 a 58 m² · 1 ou 2 dormitórios · 160 lofts", "loft"],
  ["lake-office", "Lake Office", "Business center · 2029", "Seu próximo endereço profissional.", "Salas e lajes corporativas conectadas ao Mall, à marina e ao ritmo da orla.", "52 a 510 m² · 222 salas · acesso direto ao Mall", "office"],
  ["lake-mall", "Lake Mall", "Shopping conceito · 2029", "O coração de convívio.", "Gastronomia, serviços e encontros com a água como paisagem todos os dias.", "42 a 632 m² · 32 lojas · rooftop e heliponto", "mall"]
] as const;
const pillars = [["Morar", "Sky · Garden · Park", Building2], ["Investir", "Loft · Office · Mall", BriefcaseBusiness], ["Viver", "Praia · Beach Club · Marina", Waves], ["Pertencer", "Um endereço para poucos", Sparkles]] as const;
const exclusiveFeatures = [
  ["Segurança 24h", "Portaria e eclusas para pedestres e veículos."],
  ["Tecnologia e automação", "Inovação em sistemas construtivos."],
  ["Vaga para carro elétrico", "Sistema de gerenciamento de carga."],
  ["Piscinas com borda infinita", "Vista permanente para o lago."],
  ["Espaços fitness exclusivos", "Academia de alto padrão por torre."],
  ["Beach Club exclusivo", "Praia privativa para moradores e convidados."],
  ["Marina própria", "Atracação para pequenas e médias embarcações."],
  ["Heliponto", "Acesso por terra, água e ar."],
] as const;

function DevelopmentCard({ item, index }: { item: (typeof developments)[number]; index: number }) {
  const [slug, name, eyebrow, title, description, detail, accent] = item;
  return <Link href={`/palmas-lake/${slug}`} className={`palmas-development-card palmas-development-card--${accent}`} aria-label={`Conheça o ${name}`}>
    <div className="palmas-development-image"><Image src={`/brand/palmas-lake/${accent}.jpg`} alt={`Interiores do ${name}`} fill sizes="(max-width: 700px) 100vw, 33vw" /><span className="palmas-development-shade" /><span className="palmas-development-number">0{index + 1}</span><span className="palmas-development-arrow"><ArrowUpRight size={19} /></span></div>
    <div className="palmas-development-copy"><p className="palmas-card-eyebrow">{eyebrow}</p><h3>{name}</h3><p className="palmas-development-title">{title}</p><p className="palmas-development-description">{description}</p><span className="palmas-development-detail">{detail}</span></div>
  </Link>;
}

export default function PalmasLakePage() {
  return <div className="palmas-lake-page">
    <section className="palmas-lake-hero" id="inicio"><Image src="/brand/palmas-lake/hero-principal.png" alt="Palmas Lake, Marina e torres residenciais ao pôr do sol" fill priority sizes="100vw" className="palmas-lake-hero-image" /><div className="palmas-lake-hero-overlay" /><div className="palmas-lake-hero-grain" />
      <div className="palmas-lake-container palmas-lake-nav"><Link href="#inicio" className="palmas-lake-wordmark" aria-label="Palmas Lake, início"><span>PALMAS</span><strong>LAKE</strong></Link><nav aria-label="Navegação Palmas Lake"><Link href="#complexo">O complexo</Link><Link href="#experiencias">Experiências</Link><Link href="#endereco">O endereço</Link><Link href="#marina">Marina</Link></nav><a href={whatsappHref} target="_blank" rel="noreferrer" className="palmas-lake-nav-button">Falar com especialista <ArrowUpRight size={15} /></a></div>
      <div className="palmas-lake-container palmas-lake-hero-content"><p className="palmas-lake-eyebrow"><span /> Complexo multifuncional à beira-lago</p><p className="palmas-lake-hero-location"><MapPin size={15} /> Palmas · Tocantins</p><h1>Onde a vida<br /><em>se eleva.</em></h1><p className="palmas-lake-hero-lede">Um novo horizonte para morar, trabalhar, investir e viver a orla de Palmas.</p><div className="palmas-lake-hero-actions"><Link href="#experiencias" className="palmas-lake-button palmas-lake-button--light">Descobrir o complexo <ArrowDownRight size={17} /></Link><a href={whatsappHref} target="_blank" rel="noreferrer" className="palmas-lake-hero-text-link">Agendar uma conversa <ArrowUpRight size={16} /></a></div></div>
      <div className="palmas-lake-container palmas-lake-scroll-cue"><span /> Role para explorar <ChevronDown size={16} /></div>
    </section>
    <div className="palmas-lake-stats"><div className="palmas-lake-container palmas-lake-stats-grid"><div><strong>1</strong><span>Endereço único</span></div><div><strong>6</strong><span>Experiências</span></div><div><strong>111.817 m²</strong><span>Área total construída</span></div><div><strong>22.207 m²</strong><span>Área do terreno</span></div><div><strong>∞</strong><span>Possibilidades</span></div></div></div>
    <section className="palmas-lake-section palmas-lake-intro" id="complexo"><div className="palmas-lake-container palmas-lake-intro-grid"><div><p className="palmas-lake-kicker">Um destino, muitas formas de viver</p><h2>O lago como paisagem. A cidade como horizonte.</h2></div><div className="palmas-lake-intro-copy"><p>O Palmas Lake nasce da união entre raízes locais, visão global e um endereço raro: a entrada da ponte, de frente para o Lago de Palmas.</p><p>Um ecossistema completo que aproxima a casa, o trabalho, o lazer e os encontros — com praia exclusiva, Beach Club, marina própria e o pôr do sol mais deslumbrante da cidade.</p><Link href="#experiencias" className="palmas-lake-inline-link">Conheça as seis experiências <ArrowDownRight size={16} /></Link></div></div></section>
    <section className="palmas-lake-overview"><div className="palmas-lake-overview-image"><Image src="/brand/palmas-lake/complex.jpg" alt="Vista geral do complexo Palmas Lake com a Marina" fill sizes="100vw" /><span className="palmas-lake-overview-shade" /></div><div className="palmas-lake-container palmas-lake-overview-copy"><p className="palmas-lake-kicker">Um complexo, seis experiências</p><h2>Todos os caminhos levam ao lago.</h2><p>Torres residenciais, Loft, Office e Mall se conectam em um único destino à beira da água. A Marina e as áreas de convivência fazem parte dessa experiência compartilhada.</p><div className="palmas-lake-overview-tags"><span><Waves size={16} /> Vista para o lago</span><span><Anchor size={16} /> Marina própria</span><span><Building2 size={16} /> Seis experiências</span></div></div></section>
    <section className="palmas-lake-exclusive" id="exclusivos" aria-labelledby="palmas-lake-exclusive-title"><div className="palmas-lake-container palmas-lake-exclusive-grid"><div className="palmas-lake-exclusive-copy"><p className="palmas-lake-kicker">O que só o Palmas Lake entrega</p><h2 id="palmas-lake-exclusive-title">Um novo padrão de viver o lago.</h2><p>Uma estrutura pensada para aproximar segurança, tecnologia, lazer e mobilidade em um só endereço — com experiências que não se encontram em outro lugar de Palmas.</p><div className="palmas-lake-exclusive-list">{exclusiveFeatures.map(([title, detail], index) => <article key={title}><span>0{index + 1}</span><div><h3>{title}</h3><p>{detail}</p></div></article>)}</div></div><figure className="palmas-lake-exclusive-image"><Image src="/brand/palmas-lake/helipad.webp" alt="Vista do Palmas Lake com acesso por terra, água e ar" fill sizes="(max-width: 900px) 100vw, 42vw" /><span><Plane size={16} /> Acesso por terra, água e ar</span></figure></div></section>
    <section className="palmas-lake-section palmas-lake-pillars"><div className="palmas-lake-container"><div className="palmas-lake-section-heading"><p className="palmas-lake-kicker">Mais que um empreendimento</p><h2>Quatro maneiras de pertencer ao mesmo endereço.</h2></div><div className="palmas-lake-pillars-grid">{pillars.map(([label, detail, Icon], index) => <div className="palmas-lake-pillar" key={label}><span className="palmas-lake-pillar-number">0{index + 1}</span><Icon size={22} strokeWidth={1.35} /><h3>{label}</h3><p>{detail}</p></div>)}</div></div></section>
    <section className="palmas-lake-section palmas-lake-lifestyle" id="endereco"><div className="palmas-lake-container palmas-lake-lifestyle-grid"><div className="palmas-lake-lifestyle-image"><Image src="/brand/palmas-lake/pool-lake-view.jpg" alt="Piscina de borda infinita com vista para o Lago de Palmas" fill sizes="(max-width: 800px) 100vw, 50vw" /><span><Waves size={16} /> Áreas comuns compartilhadas</span></div><div className="palmas-lake-lifestyle-copy"><p className="palmas-lake-kicker">Um estilo de vida de resort</p><h2>O seu dia pode começar na água.</h2><p>A brisa do lago pela manhã, a areia quente da praia à tarde, o horizonte inteiro visto da piscina ao anoitecer. No Palmas Lake, a paisagem não é um detalhe — ela faz parte da rotina de todos os empreendimentos.</p><div className="palmas-lake-feature-list"><span><Anchor size={16} /> Marina própria para pequenas e médias embarcações</span><span><Waves size={16} /> Praia exclusiva para moradores e convidados</span><span><ShieldCheck size={16} /> Beach Club, piscinas, esporte e convivência</span><span><Plane size={16} /> Heliponto e acesso por terra, água e ar</span></div></div></div></section>
    <section className="palmas-lake-marina" id="marina" aria-labelledby="palmas-lake-marina-title"><div className="palmas-lake-container palmas-lake-marina-intro"><div className="palmas-lake-marina-copy"><p className="palmas-lake-kicker">Praia exclusiva, Beach Club e Marina própria</p><h2 id="palmas-lake-marina-title">A cidade termina onde começa a sua experiência no lago.</h2><p>Uma praia privativa para moradores e convidados, um Beach Club exclusivo e uma Marina própria para viver Palmas por terra e por água — com a paisagem sempre por perto.</p></div><div className="palmas-lake-marina-feature"><Image src="/brand/palmas-lake/marina-beach-official.jpg" alt="Marina e praia do Palmas Lake diante das torres do complexo" fill sizes="(max-width: 900px) 100vw, 58vw" /><span><Anchor size={15} /> Marina · Praia · Beach Club</span></div></div><div className="palmas-lake-container palmas-lake-marina-details"><figure className="palmas-lake-marina-panorama"><Image src="/brand/palmas-lake/marina-praia-anexo.png" alt="Marina do Palmas Lake com embarcações e praia privativa ao fundo" fill sizes="(max-width: 900px) 100vw, 55vw" /><figcaption>Um horizonte que também se acessa pela água.</figcaption></figure><div className="palmas-lake-marina-points"><article><span>01</span><h3>Beach Club exclusivo</h3><p>Praia privativa para moradores e convidados.</p></article><article><span>02</span><h3>Marina própria</h3><p>Atracação para pequenas e médias embarcações.</p></article></div></div></section>
    <section className="palmas-lake-sunset" aria-labelledby="palmas-lake-sunset-title"><div className="palmas-lake-sunset-image"><Image src="/brand/palmas-lake/sunset-pool.jpg" alt="Pôr do sol sobre o Lago de Palmas visto de uma piscina de borda infinita" fill sizes="100vw" /></div><div className="palmas-lake-container palmas-lake-sunset-copy"><p className="palmas-lake-kicker">O horizonte de Palmas</p><h2 id="palmas-lake-sunset-title">O pôr do sol exclusivo de Palmas.</h2><p>Uma vista para todos os dias, emoldurada pela água e pela luz que transforma a cidade ao fim da tarde. No Palmas Lake, esse horizonte não é uma visita — é parte definitiva da sua rotina.</p><div className="palmas-lake-sunset-tags"><span>Vista de todos os dias</span><span>Exclusividade à beira do lago</span><span>Um horizonte definitivo</span></div></div></section>
    <section className="palmas-lake-gallery"><div className="palmas-lake-container"><div className="palmas-lake-gallery-grid"><figure className="palmas-lake-gallery-card palmas-lake-gallery-card--wide"><Image src="/brand/palmas-lake/complex.jpg" alt="Vista do complexo Palmas Lake e sua Marina" fill sizes="(max-width: 700px) 100vw, 66vw" /><figcaption><span>01</span><strong>O complexo à beira do lago</strong><small>Seis experiências, um destino único</small></figcaption></figure><figure className="palmas-lake-gallery-card"><Image src="/brand/palmas-lake/office.jpg" alt="Arquitetura da torre multifuncional Palmas Lake" fill sizes="(max-width: 700px) 100vw, 33vw" /><figcaption><span>02</span><strong>Trabalho e encontros</strong><small>Lake Office conectado ao Mall</small></figcaption></figure><figure className="palmas-lake-gallery-card"><Image src="/brand/palmas-lake/mall.jpg" alt="Arquitetura do Lake Mall" fill sizes="(max-width: 700px) 100vw, 33vw" /><figcaption><span>03</span><strong>Convívio com vista</strong><small>Gastronomia, serviços e rooftop</small></figcaption></figure></div></div></section>
    <section className="palmas-lake-amenities" aria-labelledby="palmas-lake-amenities-title"><div className="palmas-lake-container"><div className="palmas-lake-section-heading"><p className="palmas-lake-kicker">Estrutura para viver o complexo</p><h2 id="palmas-lake-amenities-title">Espaços para cada ritmo do seu dia.</h2><p>Esporte, encontros, lazer e serviços pensados para transformar o Palmas Lake em um destino completo.</p></div><div className="palmas-lake-amenities-grid"><figure className="palmas-lake-amenity-card"><Image src="/brand/palmas-lake/sports-court.jpg" alt="Quadra de basquete e society do Palmas Lake" fill sizes="(max-width: 700px) 100vw, 33vw" /><figcaption><strong>Esporte e movimento</strong><small>Quadra de basquete e society</small></figcaption></figure><figure className="palmas-lake-amenity-card"><Image src="/brand/palmas-lake/lake-mall-events.jpg" alt="Salão de eventos do Lake Mall" fill sizes="(max-width: 700px) 100vw, 33vw" /><figcaption><strong>Eventos com vista</strong><small>Salão de eventos do Lake Mall</small></figcaption></figure><figure className="palmas-lake-amenity-card"><Image src="/brand/palmas-lake/beach-tennis.jpg" alt="Quadra de beach tennis do Palmas Lake" fill sizes="(max-width: 700px) 100vw, 33vw" /><figcaption><strong>Beach tennis à beira do lago</strong><small>Quadra de beach tennis</small></figcaption></figure><figure className="palmas-lake-amenity-card"><Image src="/brand/palmas-lake/pet-place.jpg" alt="Pet Place do Palmas Lake" fill sizes="(max-width: 700px) 100vw, 33vw" /><figcaption><strong>Pet Place</strong><small>Um espaço pensado para eles</small></figcaption></figure><figure className="palmas-lake-amenity-card"><Image src="/brand/palmas-lake/lake-mall-facade.jpg" alt="Fachada do shopping Lake Mall" fill sizes="(max-width: 700px) 100vw, 33vw" /><figcaption><strong>Lake Mall</strong><small>Fachada do shopping conceito</small></figcaption></figure><figure className="palmas-lake-amenity-card"><Image src="/brand/palmas-lake/pool-lake-view.jpg" alt="Piscina suspensa com borda infinita e vista para o lago nos Lofts" fill sizes="(max-width: 700px) 100vw, 33vw" /><figcaption><strong>Piscina suspensa dos Lofts</strong><small>Borda infinita com vista para o lago</small></figcaption></figure></div></div></section>
    <section className="palmas-lake-section palmas-lake-experiences" id="experiencias"><div className="palmas-lake-container"><div className="palmas-lake-section-heading palmas-lake-section-heading--wide"><p className="palmas-lake-kicker">Escolha o seu horizonte</p><h2>Seis experiências.<br /><em>Um só Palmas Lake.</em></h2><p>Conheça cada empreendimento e descubra qual parte desse novo destino combina com o seu próximo capítulo.</p></div><div className="palmas-lake-developments-grid">{developments.map((item, index) => <DevelopmentCard key={item[0]} item={item} index={index} />)}</div></div></section>
    <section className="palmas-lake-broker"><div className="palmas-lake-container palmas-lake-broker-grid"><div className="palmas-lake-broker-image"><Image src="/brand/pedro-portrait-1.png" alt="Pedro Soares, corretor oficial do Palmas Lake" fill sizes="(max-width: 800px) 100vw, 38vw" /><span>Atendimento oficial<br />Palmas Lake</span></div><div className="palmas-lake-broker-copy"><p className="palmas-lake-kicker">Seu especialista no projeto</p><h2>Conheça o Palmas Lake com quem entende o seu próximo passo.</h2><p>Eu sou Pedro Soares, corretor oficial do Palmas Lake. Vou ajudar você a comparar as seis experiências e escolher a que faz sentido para morar, investir ou empreender.</p><div className="palmas-lake-broker-points"><span>Leitura personalizada do complexo</span><span>Apresentação das tipologias e áreas comuns</span><span>Atendimento direto e consultivo</span></div><a href={whatsappHref} target="_blank" rel="noreferrer" className="palmas-lake-button palmas-lake-button--gold">Falar com Pedro <ArrowUpRight size={17} /></a></div></div></section>
    <PalmasLakeLeadForm />
    <section className="palmas-lake-enterprise" aria-labelledby="palmas-lake-enterprise-title"><div className="palmas-lake-container palmas-lake-enterprise-grid"><div className="palmas-lake-enterprise-copy"><p className="palmas-lake-kicker">O empreendimento</p><h2 id="palmas-lake-enterprise-title">A fusão perfeita.</h2><p>O Palmas Lake nasce da fusão entre a autenticidade das raízes locais da Melk Urbanizadora e Incorporadora, a ousadia da visão global da SL Empreendimentos e a solidez da União do Lago Loteamentos e Investimentos.</p><p>Juntas, transformam a paisagem urbana de Palmas, trazendo uma verdadeira evolução no conceito de viver — um marco que celebra a energia da cidade e a serenidade do lago no mesmo endereço.</p></div><div className="palmas-lake-enterprise-image"><Image src="/brand/palmas-lake/enterprise-architecture.jpg" alt="Arquitetura contemporânea do Palmas Lake diante do lago" fill sizes="(max-width: 900px) 100vw, 45vw" /><span>Um novo marco para Palmas</span></div></div><div className="palmas-lake-container palmas-lake-enterprise-partners"><article className="palmas-lake-enterprise-partner palmas-lake-enterprise-partner--melk"><div className="palmas-lake-enterprise-logo palmas-lake-enterprise-logo--image"><Image src="/brand/palmas-lake/melk-logo.png" alt="Melk Urbanizadora e Incorporadora" fill sizes="116px" /></div><p>Urbanizadora e Incorporadora</p><small>A alma local, raízes e história em Palmas.</small></article><article className="palmas-lake-enterprise-partner"><div className="palmas-lake-enterprise-logo"><strong>SL</strong><span>EMPREENDIMENTOS</span></div><p>Desenvolvedora e gestora estratégica</p><small>Visão global e experiência em grandes projetos.</small></article><article className="palmas-lake-enterprise-partner"><div className="palmas-lake-enterprise-logo palmas-lake-enterprise-logo--union"><strong>UNIÃO</strong><span>DO LAGO</span></div><p>Loteamentos e Investimentos</p><small>A solidez que projeta o futuro e fomenta a economia.</small></article></div></section>
    <section className="palmas-lake-final-cta"><div className="palmas-lake-container palmas-lake-final-cta-inner"><p className="palmas-lake-kicker">Uma nova relação com a cidade</p><h2>Vamos elevar<br /><em>a sua vida?</em></h2><p>Conheça o Palmas Lake de perto e encontre a experiência que faz sentido para você.</p><a href={whatsappHref} target="_blank" rel="noreferrer" className="palmas-lake-button palmas-lake-button--gold">Quero conhecer o Palmas Lake <ArrowUpRight size={17} /></a></div></section>
    <footer className="palmas-lake-footer"><div className="palmas-lake-container palmas-lake-footer-grid"><Link href="#inicio" className="palmas-lake-wordmark" aria-label="Voltar ao início"><span>PALMAS</span><strong>LAKE</strong></Link><p>Onde a vida se eleva.<br />Alameda ALC N.º 14 · Palmas · Tocantins</p><div className="palmas-lake-footer-technical"><strong>Dados técnicos essenciais.</strong><span>Área total construída: 111.817,34 m² · Terreno: 22.206,98 m².</span></div><p className="palmas-lake-footer-note">Imagens meramente ilustrativas. Informações sujeitas a alteração sem aviso prévio.</p></div></footer>
    <PalmasLakeWhatsAppBubble />
  </div>;
}
